# Generated by Django 3.0.5 on 2020-04-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_sum',
            field=models.TextField(),
        ),
    ]
